sudo: false
language: python
python:
- 2.7
install:
- pip install tox-travis
- pip install coverage coveralls
script:
- tox -r
- python setup.py sdist
branches:
  except:
  - master
deploy:
- provider: releases
  api_key:
    secure: Vbz1ISaRWxW5qPQji80s8MZvrN7WRBtcdNTgzv16kayXfAG1di38CViT/Tx787E8cn9LaSprt5O/uliXr39xmT7nC6iO+OZV+j/X2i0GRX0LiHh48gSfEauJ5raCgskPGVQe7X9AUMh7F0TnLBE+Fk8w+R4sZD7ZdeCsDqtTsxnGWlaRBqszGFJLlXlIUJDhyALSHCBcb/u27k13SBHZjQeXvUSpr9mXsMMKkJQVOtPxgCpRJFdhg4OEfvxXWfKpTPWlRQKlYiflVGOGmCW1jU4jeOFqyrAtYhe1ZTIt4WxQgVs4/28B3FXL07OUMYkbPWTsDjGy7qT+YvGri97hgKIdJfnQbM62fNyFMJ0+xtZzRb4wHHVALUvFR3FELf4UUGacI0TaSmn8iXZWWi1kKRqXAmP5ANyqliecG2vHLJVKxeJgpX9CiKX24dZ+bZ9h117cAoS2YBn91Yk+xKfCdf1c56wFvYK6gZ9whtuCtYofA3iBOJO4yRnIDF/A3daluLX6LaqbHTmoDdGCjH56oRhzimFHbnvSEPswacAl8B5RUPuiKM+ZUhVV/8DK2cGy0ZvI2YBwZ2bXfrvvHekrjbsCYNBZcpAC56aLUqb5RieOj8tEJyKwjk7GUwiHmG947DN2zY/D3GmMvTt6OsMcOEUvaVgJh4HaFbc3nToXI1I=
  file: dist/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: 3stack-software/tabula-py
- provider: script
  script: bash .dist_gemfury.sh
  skip_cleanup: true
  on:
    tags: true
