sudo: false
language: python
python:
- 3.6
install:
- pip install tox-travis
- pip install coverage coveralls
script:
- tox -r
- python setup.py sdist
branches:
  except:
  - master
deploy:
- provider: releases
  api_key:
    secure: S8bkt4SOgLtQFL/suya1Tmpamge+oqCP/lueyEigMXmlQWFDNwy3hGMWlpudslbmcF0n38mpNnYZX5IJe1zb7ds8V54yjMxZ8D4KKV0qo4jPnRbD1FN/ionBNYMeEE9G0ht/TKt6laIv6stsKFKWACKL/IbJ2D9qfNBko/76sl72Zcp0uLxAuuB7vySbnwhdbSlJmpmqzUOjdTykJcNS2KMzUdQnaF/t2kIgSdIVJXBYJYNNxeZ4HWeEVBiOkrWMt/UJeVutYLUrpkBbOlNED2iK03CBsi/wAv0nl7oSjSdnrrKtrtBMT1PXq4ElvAX1o2xAqLG37eU6o7pdKq+K5yNgbl3/03o7b8pE8rrr+qYgWYNxEGVFH2hBPz42oacSJNg/nNV1SpoGh6RnZL6orAqTT0QZptYDs7jCj3vy36ALjn62Kbp/+DuCe8ELGhGcYQzVPMg5IEixqqKK3tvb9NkxHuYiuAg9wf9kN0NpP/9hDNTcY5hODD827K3UA3QoENvRWxVUl7HO5HLAJcVjSdoXuSI5tRt/3WKC2tPYtiykzmeRDC7wj918LQ/dQocNBgX5uWll3E0Yghn1RfMULTUurmhDLnrETNKx3UDCMXcHhfAZWN/jGF+4bxoS+vrD3AZwZ1r5fjlMHmrCbzP7yI9gXecs6oE95pY9s2jRoy8=
  file: dist/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: 3stack-software/tabula-py
- provider: script
  script: bash .dist_gemfury.sh
  skip_cleanup: true
  on:
    tags: true
